export const GET_LEAGUE_INFOS = 'GET_LEAGUE_INFOS';
export const GET_LEAGUE_INFOS_SUCCESS = 'GET_LEAGUES_INFOS_SUCCESS';
export const GET_LEAGUE_INFOS_ERROR = 'GET_LEAGUES_INFOS_ERROR';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS';
export const GET_ALL_TEAMS_ERROR = 'GET_ALL_TEAMS_ERROR';
export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_ALL_PLAYERS_SUCCESS = 'GET_ALL_PLAYERS_SUCCESS';
export const GET_ALL_PLAYERS_ERROR = 'GET_ALL_PLAYERS_ERROR';
export const GET_PLAYER_DETAIL = 'GET_PLAYER_DETAIL';
export const GET_PLAYER_DETAIL_CONTRACT = 'GET_PLAYER_DETAIL_CONTRACT';
export const GET_PLAYER_DETAIL_TEAMS = 'GET_PLAYER_DETAIL_TEAMS';
export const GET_PLAYER_DETAIL_HONOURS = 'GET_PLAYER_DETAIL_HONOURS';
export const GET_PLAYER_DETAIL_ERROR = 'GET_PLAYER_DETAIL_ERROR';
export const GET_TEAM_CALENDAR = 'GET_TEAM_CALENDAR';
export const GET_TEAM_CALENDAR_NEXT = 'GET_TEAM_CALENDAR_NEXT';
export const GET_TEAM_CALENDAR_LAST = 'GET_TEAM_CALENDAR_LAST';
export const GET_TEAM_CALENDAR_ERROR = 'GET_TEAM_CALENDAR_ERROR';

export const GET_HIGHLIGHTS = 'GET_HIGHLIGHTS';
export const GET_HIGHLIGHTS_L1_SUCCESS = 'GET_HIGHLIGHTS_L1_SUCCESS';
export const GET_HIGHLIGHTS_L2_SUCCESS = 'GET_HIGHLIGHTS_L2_SUCCESS';
export const GET_HIGHLIGHTS_N1_SUCCESS = 'GET_HIGHLIGHTS_N1_SUCCESS';
export const GET_HIGHLIGHTS_ERROR = 'GET_HIGHLIGHTS_ERROR';

export const GET_LIVE_SCORE_L1 = 'GET_LIVE_SCORE_L1';
export const GET_LIVE_SCORE_L2 = 'GET_LIVE_SCORE_L2';
export const GET_LIVE_SCORE_N1 = 'GET_LIVE_SCORE_N1';
export const GET_LIVE_SCORE_L1_SUCCESS = 'GET_LIVE_SCORE_L1_SUCCESS';
export const GET_LIVE_SCORE_L2_SUCCESS = 'GET_LIVE_SCORE_L2_SUCCESS';
export const GET_LIVE_SCORE_N1_SUCCESS = 'GET_LIVE_SCORE_N1_SUCCESS';
export const GET_LIVE_SCORE_ERROR = 'GET_LIVE_SCORE_ERROR';

export const GET_LAST_SCORE_L1 = 'GET_LAST_SCORE_L1';
export const GET_LAST_SCORE_L2 = 'GET_LAST_SCORE_L2';
export const GET_LAST_SCORE_N1 = 'GET_LAST_SCORE_N1';
export const GET_LAST_SCORE_L1_SUCCESS = 'GET_LAST_SCORE_L1_SUCCESS';
export const GET_LAST_SCORE_L2_SUCCESS = 'GET_LAST_SCORE_L2_SUCCESS';
export const GET_LAST_SCORE_N1_SUCCESS = 'GET_LAST_SCORE_N1_SUCCESS';
export const GET_LAST_SCORE_ERROR = 'GET_LAST_SCORE_ERROR';
export const GET_LOGO = 'GET_LOGO';
export const GET_LOGO_SUCCESS = 'GET_LOGO_SUCCESS';
export const POST_NAV = 'POST_NAV';
export const GET_EVENT_DETAIL = 'GET_EVENT_DETAIL';
export const GET_EVENT_DETAIL_STATS_SUCCESS = 'GET_EVENT_DETAIL_STATS_SUCCESS';
export const GET_EVENT_DETAIL_TIMELINE_SUCCESS = 'GET_EVENT_DETAIL_TIMELINE_SUCCESS';


export const GET_NEXT_SCORE_L1 = 'GET_NEXT_SCORE_L1';
export const GET_NEXT_SCORE_L2 = 'GET_NEXT_SCORE_L2';
export const GET_NEXT_SCORE_N1 = 'GET_NEXT_SCORE_N1';
export const GET_NEXT_SCORE_L1_SUCCESS = 'GET_NEXT_SCORE_L1_SUCCESS';
export const GET_NEXT_SCORE_L2_SUCCESS = 'GET_NEXT_SCORE_L2_SUCCESS';
export const GET_NEXT_SCORE_N1_SUCCESS = 'GET_NEXT_SCORE_N1_SUCCESS';
export const GET_NEXT_SCORE_ERROR = 'GET_NEXT_SCORE_ERROR';

export const GET_RANKING_L1 = 'GET_RANKING_L1';
export const GET_RANKING_L2 = 'GET_RANKING_L2';
export const GET_RANKING_N1 = 'GET_RANKING_N1';
export const GET_RANKING_L1_SUCCESS = 'GET_RANKING_L1_SUCCESS';
export const GET_RANKING_L2_SUCCESS = 'GET_RANKING_L2_SUCCESS';
export const GET_RANKING_N1_SUCCESS = 'GET_RANKING_N1_SUCCESS';
export const GET_RANKING_ERROR = 'GET_RANKING_ERROR';
