export const GET_LEAGUE_INFOS = 'GET_LEAGUE_INFOS';
export const GET_LEAGUE_INFOS_SUCCESS = 'GET_LEAGUES_INFOS_SUCCESS';
export const GET_LEAGUE_INFOS_ERROR = 'GET_LEAGUES_INFOS_ERROR';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS';
export const GET_ALL_TEAMS_ERROR = 'GET_ALL_TEAMS_ERROR';
export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_ALL_PLAYERS_SUCCESS = 'GET_ALL_PLAYERS_SUCCESS';
export const GET_ALL_PLAYERS_ERROR = 'GET_ALL_PLAYERS_ERROR';

export const GET_HIGHLIGHTS = 'GET_HIGHLIGHTS';
export const GET_HIGHLIGHTS_NBA_SUCCESS = 'GET_HIGHLIGHTS_NBA_SUCCESS';
export const GET_HIGHLIGHTS_MLB_SUCCESS = 'GET_HIGHLIGHTS_MLB_SUCCESS';
export const GET_HIGHLIGHTS_NHL_SUCCESS = 'GET_HIGHLIGHTS_NHL_SUCCESS';
export const GET_HIGHLIGHTS_NFL_SUCCESS = 'GET_HIGHLIGHTS_NFL_SUCCESS';
export const GET_HIGHLIGHTS_MLS_SUCCESS = 'GET_HIGHLIGHTS_MLS_SUCCESS';
export const GET_HIGHLIGHTS_ERROR = 'GET_HIGHLIGHTS_ERROR';
