export const GET_LEAGUE_INFOS = 'GET_LEAGUE_INFOS';
export const GET_LEAGUE_INFOS_SUCCESS = 'GET_LEAGUES_INFOS_SUCCESS';
export const GET_LEAGUE_INFOS_ERROR = 'GET_LEAGUES_INFOS_ERROR';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_TEAMS_SUCCESS = 'GET_ALL_TEAMS_SUCCESS';
export const GET_ALL_TEAMS_ERROR = 'GET_ALL_TEAMS_ERROR';
